const checkbox = document.getElementById('checkbox')
const label = document.querySelector('.label')
const ball = document.querySelector('.ball')
const bg = document.querySelector('.bg')
const card1 = document.getElementById('card1')
const card2 = document.getElementById('card2')
const card3 = document.getElementById('card3')
const card4 = document.getElementById('card4')
const Inner1 = document.getElementById('inner1')
const Inner2 = document.getElementById('inner2')
const Inner3 = document.getElementById('inner3')
const Inner4 = document.getElementById('inner4')
const Inner5 = document.getElementById('inner5')
const Inner6 = document.getElementById('inner6')
const Inner7 = document.getElementById('inner7')
const Inner8 = document.getElementById('inner8')
const p1 = document.getElementById('para1')
const p2 = document.getElementById('para2')
const p3 = document.getElementById('para3')
const p4 = document.getElementById('para4')
const p5 = document.getElementById('para5')
const p6 = document.getElementById('para6')
const p7 = document.getElementById('para7')
const p8 = document.getElementById('para8')

checkbox.addEventListener('change', () => {
  document.body.classList.toggle('light')
  label.classList.toggle('light')
  ball.classList.toggle('light')
  bg.classList.toggle('light')
  card1.classList.toggle('light')
  card2.classList.toggle('light')
  card3.classList.toggle('light')
  card4.classList.toggle('light')
  Inner1.classList.toggle('light')
  Inner2.classList.toggle('light')
  Inner3.classList.toggle('light')
  Inner4.classList.toggle('light')
  Inner5.classList.toggle('light')
  Inner6.classList.toggle('light')
  Inner7.classList.toggle('light')
  Inner8.classList.toggle('light')
  p1.classList.toggle('light')
  p2.classList.toggle('light')
  p3.classList.toggle('light')
  p4.classList.toggle('light')
  p5.classList.toggle('light')
  p6.classList.toggle('light')
  p7.classList.toggle('light')
  p8.classList.toggle('light')
})
